[package]
name = "rust-test-compress-decompress"
version = "0.1.0"
edition = "2021"

[dependencies]
zstd = {version = "0.13.2", features = ["zstdmt"] }
tar = "0.4.41"
flate2 = "1.0.30"
clap = { version = "4.5.9", features = ["derive"] }
num_cpus = "1.16.0"