[package]
name = "compressimagesvideosrust"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.1"
walkdir = "2.5.0"
num_cpus = "1.16.0"
zip = "2.1.3"
rayon = "1.10.0"
memmap = "0.7.0"
tokio = { version = "1.38.0", features = ["full"] }
futures = "0.3.30"